cisba = ["Nastavte barvu pro zrychtované částě okna","Set the colour for the cleaned parts of the window","Legen Sie die Farbe für die gereinigten Teile des Fensters fest","Nastavte barvu pro vyčišťěné částě okna"]
spinba = ["Nastavte barvu pro zaprasené částě okna","Set the colour for the dirty parts of the window","Legen Sie die Farbe für die verschmutzten Teile des Fensters fest","Nastavte barvu pro špinavé částě okna"]
ramba = ["Nastavte barvu okeňého ráma","Set the colour for the window frame","Legen Sie die Farbe für den Fensterrahmen fest","Nastavte barvu pro rám okna"]
zdiba = ["Nastavte barvu zdě, na kterej je okno","Set the colour of the wall where the window is","Legen Sie die Farbe der Wand fest, an der sich das Fenster befindet","Nastavte barvu zdi, na které je okno"]
bar1 = ["Nastavte barvu texta","Set the text colour","Einstellung der Textfarbe","Nastavte barvu textu"]
bar2 = ["Nastavte barvu pro pozaďé","Set the background colour","Einstellung der Hintergrundfarbe","Nastavte barvu pro pozadí"]
znas = ["Zpěť","Back","Zurück"]
kontrot = ["Zkontrolovať otázku","Check the question","Prüfen der Frage","Zkontrolovat otázku"]
spust = ["Spustiť","Start","Start","Spustit"]
nast = ["Nastaveňé","Settings","Einstellungen","Nastavení"]
vyčok = ["Zrychtovat okno","Clean the window","Das Fenster reinigen","Vyčistit okno"]
vyčnic = ["Nepovedlo sa Vám zrychtovat okno","You failed to clean the window","Sie haben es versäumt, das Fenster zu putzen","Nepovedlo se Vám vyčistit okno"]
vyčvíc = ["Zrychtovali ste {}/{} okna","You cleaned {}/{} of the window","Sie haben {}/{} Fenster geputz","Vyčistili jste {}/{} okna"]
vyčvše = ["Zrychtovali ste celé okno","You cleaned the whole window","Du hast das ganze Fenster geputzt","Vyčistili jste celé okno"]
znov = ["Zkusiť znova","Try again","Erneut versuchen","Zkusit znovu"]
exit = ["Odjísť","Leave","Verlassen Sie","Odejít"]
jaz = ["Jazuk","Language","Sprache","Jazyk"]
zavritw = ["Zatvoriť okno","Close window","Fenster schließen","Zyvřít okno"]
moravstina = ["Moravšina","Moravian","Mährisch","Moravšťina"]
anglictina = ["Anglečtina","English","English","Angličtina"]
nemcina = ["Dederónština","German","Deutsch","Němčina"]
cestina = ["Čecháčština","Czech","Tschechisch","Čeština"]
restart_okna_t = ["Restartovať","Restart","Neustart","Restartovat"]
restart_okna = ["Aby sa projevily změny, mosíme aplikacu restartovať","We need to restart the application for the changes to take effect","Wir müssen die Anwendung neu starten, damit die Änderungen wirksam werden","Aby se projevily změny, musíme aplikaci restartovat"]

#prohodit moravštinu s češtinou